[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
reddit_dapp = "9X2dUhxQaKzATkvL7XQdSME1geQM7JmX3odyUmXugZKm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
